[package]
name = "consistent_hash_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
consistent_hash = "0.1.4"
murmur3 = "0.5.2"
rand = "0.8.5"
substring = "1.4.5"
